#!/usr/bin/env ruby

require "optparse"

@flags = {
  :aur => false,
  :scan => false,
  :verbose => false,
}

opt = OptionParser.new
opt.version = "0.0.1"
opt.on("-a", "--include-aur", help = "Include packages of AUR. (very slow)") { @flags[:aur] = true }
opt.on("-s", "--scan", help = "Scan for packages that not exist.") { @flags[:scan] = true }
opt.on("-v", "--verbose", help = "Verbose output.") { @flags[:verbose] = true }
opt.parse!(ARGV)

if @flags[:scan]
  `pacman -Q`.each_line do |n|
    if n =~ /(.+?)\s.+/
      puts "Checking for #{$1}..." if @flags[:verbose]
      `#{@flags[:aur] ? "yaourt" : "pacman"} -Si #{$1}`
    end
  end
else
  puts "Error: invalid or insufficient operands."
end
